# Generated by Django 5.0.6 on 2024-06-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
