# Generated by Django 5.0.6 on 2024-06-23 08:02

import pizza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pizza.models.pizza_image_upload_to),
        ),
    ]
