# Generated by Django 5.0.6 on 2024-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
