# Generated by Django 5.0.6 on 2024-06-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_added_at_cartitem_first_added_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='last_added_at',
            new_name='last_edited_at',
        ),
    ]
