# Generated by Django 5.0.6 on 2024-06-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderPrice',
            new_name='order_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='itemPrice',
            new_name='item_price',
        ),
    ]
